### Create Report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "ford",
  "model": "mustang",
  "year": 1982,
  "lng":45,
  "lat":45,
  "mileage":50000,
  "price": 20000,
  "approved":true
}

### Approve an existing report
PATCH http://localhost:3000/reports/37
Content-Type: application/json

{
 "approved":true
}

### Get an estimate for existing vehicle
GET http://localhost:3000/reports/getestimate?make=ford&model=mustang&lat=45&lng=45&mileage=200&year=1981

### Get a single vehicle
GET http://localhost:3000/reports/23

### Get a list of all vehichles
GET http://localhost:3000/reports